version: "3.8"

services:
  redis:
    image: "redis:latest"
    container_name: redis-cache
    ports:
      - "6379:6379"
    restart: unless-stopped


  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-cache
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_DB: "0"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - web

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_USER=admin
      - GF_SECURITY_PASSWORD=admin
    volumes:
      - ./grafana/datasource/prometheus.yaml:/etc/grafana/provisioning/datasources/prometheus.yaml:ro
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/dashboards/cache-metrics.json:/var/lib/grafana/dashboards/cache-metrics.json:ro
    depends_on:
      - prometheus
    restart: unless-stopped