name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: pytest -q

      - name: Build Docker images
        run: docker-compose build

      - name: Smoke-test FastAPI
        run: |
          docker-compose up -d redis web
          sleep 5
          curl --fail http://localhost:5000/health
          docker-compose down

      - name: Lint code
        run: |
          pip install flake8
          flake8 app